### ISSUE TITLE
Possibility of InsigniaMod like CamoMod? 

### ISSUE THREAD

**Issue by ghost** [GPCracker/XModLib#1]
I am both new to WoT python modding and translating the KoreanRandom site from Russian to English, so I apologize for how confusing this question might sound. I'm also a Linux user running WoT in Wine, so that makes modding that much harder (but still easily doable). 

Essentially because of the API and D3D, the Wine/Linux WoT game client immediately and permanently crashes when you click on the Insignia slot in the camo/decoration menu while in Garage. Camo selection works fine using the client and API, but you cannot use insignias or other graphics. I don't understand why, but it seems to be making some kind of totally different system call, different than the way it handles camo and vehicle skinning. What I'm wondering is if there's anyway to mod the Camo Selection Mod to be able to select Insignias for a tank while in the Garage? Is it possible with enough work, or is it technically impossible because of how the game is coded? If there's a possibility I will setup a virtualenv and the API stuff and start tearing shit and mods apart to try and find a way. 

Thanks for the mods, sorry for the long stupid question.

**Comment by GPCracker** [comment]
First of all, GitHub issues are more suitable for bug reports, not conceptual suggestions, especially not related to the repository. So, it is a bad idea of trying discuss something like your question here.
On the other hand, Korean Random is an English-friendly forum, at least for those who don`t make too many errors while writing (Russian-only-speaking community could also use a translator if needed to understand a post). Questions like this would be better be discussed in public, you will acquire more useful information that way. However, if you need to ask somebody personally, or just attract him to the conversation, you could mention him in a post.
Returning to your question. I am not familiar with all English terminology about WoT, and I really don't fully understand what "Insignia's" are. And.. you would be better to ask Polyacov_Yury about that, he works with tanks models more often than I do :)
So I recommend you to start a topic [here](https://koreanrandom.com/forum/forum/76-) or [here](https://koreanrandom.com/forum/forum/80-), just copy and past your "question post" there, like others from English-speaking community do.
